### ISSUE TITLE
So... if i wanna remix the project on repl.it how would i do so?

### ISSUE THREAD

**Issue by pnes** [Assfugil/reawake#1]

**Comment by asdfugil** [comment]
Attempting to change it will create a copy (= remix on glitch).

**Comment by Galaxypog** [comment]
> Attempting to change it will create a copy (= remix on glitch).

sorry for asking but could you help me with something on my repl.it, port thingy

**Comment by pnes** [comment]
> Attempting to change it will create a copy (= remix on glitch).

what do you mean?
